### ISSUE TITLE
WFTM / ICE Joint Plugin

### ISSUE THREAD

**Issue by poolpitako** [fameal/ape-tax#10]
**Description**: 

This strategy links https://ape.tax/fantombaby with https://ape.tax/fantomsfury
A `ProviderStrategy` in each vault will provided a usd fixed amount (5k usd) to a `Joint` contract which will provide liquidity to ICE/WFTM and farm ICE tokens. Once enough profit is made, the strategy will be liquidated and funds return.

**Commit (hash)**: https://github.com/poolpitako/joint-strategy/commit/7834b5199ebc5ecf82afee7b558b02dc8f872a6b

**Tag**:

**Repo**: https://github.com/poolpitako/joint-strategy

**Scope**: (List link to files)

- Joint.sol
- ProviderStrategy.sol

**Additional References or Repo** (Link to underlying protocols or relevant documents):

**Deployed Contract** (etherscan link): 

**Review Ongoing By**:
- [x] @akshaynexus
- [x] @TheRyanMiller

**Review Completed By**:
- [x] @akshaynexus
- [ ] @TheRyanMiller

**Comment by akshaynexus** [comment]
Reviewed and lgtm.Cleanup and fixes were already done in repo earlier.

**Comment by poolpitako** [comment]
Update: Added https://github.com/poolpitako/joint-strategy/pull/5 with the following changes:
 - Renamed `gov` to `governance`
 - Renamed `pendingGov` to `pendingGovernance`
 - Now Joint's harvest check for reward balance to avoid dumping tokenB balance from provider if reward == tokenB.
 - Added a loss test
