### ISSUE TITLE
BSC Ellipsis 3EPS Farming strategy

### ISSUE THREAD

**Issue by akshaynexus** [fameal/ape-tax#11]
**Description**: This strategy stakes 3EPS in the staking pool.On harvest it gets the rewards, exits early, swaps EPS to BUSD then adds liquidity to 3EPS with single sided deposit with BUSD.

**Commit (hash)**: a86197d2e4ec02fc57283b659dfc04b578b001af

**Tag**: master

**Repo**: https://github.com/akshaynexus/yearnv2-3poolellipsis-strat/

**Scope**: (List link to files)
- https://github.com/akshaynexus/yearnv2-3poolellipsis-strat/blob/main/contracts/Strategy.sol

**Additional References or Repo** (Link to underlying protocols or relevant documents):

**Deployed Contract** (etherscan link): 

**Review Ongoing By**:
- [x] @poolpitako 
- [x] @Grandthrax

**Review Completed By**:
- [x] @poolpitako 
- [x] @Grandthrax

**Comment by poolpitako** [comment]
Looks good!

**Comment by Grandthrax** [comment]
Looks good!

**Comment by poolpitako** [comment]
website PR created.
https://github.com/fameal/ape-tax/pull/12

Closing!
