### ISSUE TITLE
Add chain switcher

### ISSUE THREAD

**Issue by banteg** [fameal/ape-tax#53]
It would be useful for discovery to have a switcher or a dropdown which allows connecting to chains where ape.tax is available.

Metamask has an RPC method to add/switch chains
https://docs.metamask.io/guide/rpc-api.html#wallet-addethereumchain

The needed metadata can be obtained here
https://chainid.network/chains.json

**Comment by fameal** [comment]
Using addethereumchain to change chain on Metamask doesn't work really well. You cannot do Ethereum for example. I've added a combobox to select the network and a warning for you to know you are in the wrong chain. Check it out.

**Comment by fameal** [comment]
Closed by #66
