### ISSUE TITLE
Deposit button stays disabled in several vaults

### ISSUE THREAD

**Issue by fameal** [fameal/ape-tax#98]
When approving the vault, the approve button stays on and never enables deposits.

Vault: https://ape.tax/fantombaby

**Comment by poolpitako** [comment]
Approve is working fine, the issue is deposit is grey after the vault is approved correctly.

**Comment by TBouder** [comment]
Should be fixed, I let the author confirm that and close the issue :)

**Comment by fameal** [comment]
done
